### Building model from scratch using Embedding layer 

In [2]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding


docs = ['Well done!', 'Good work',
'Great effort', 'nice work', 'Excellent!', 'Weak', 'Poor effort!', 'not good', 'poor work', 'Could have done better.']

labels = [1,1,1,1,1,0,0,0,0,0]

vocab_size = 50

encoded_docs = [one_hot(d, vocab_size) for d in docs]

encoded_docs

max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen = max_length, padding ='post')
print(padded_docs)

model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics =['acc'])

model.summary()

model.fit(padded_docs, labels, verbose=0, epochs=50)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy %f' %(accuracy*100))

C:\Users\Admin\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### Using pretrained GLOVE Embedding 

In [4]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding


document = ['Nice Clothes!', 'Very good shop for clothes',
'Amazing clothes', 'Clothes are good', 'Superb!', 'Very bad', 'Poor quality', 'not good', 'clothes fitting bad', 'Shop not good']

labels = [1,1,1,1,1,0,0,0,0,0]

vocab_size = 40

encoded_documents = [one_hot(d, vocab_size) for d in document]

print(encoded_documents)

maxlength = 5
padded_documents = pad_sequences(encoded_documents, maxlen = maxlength, padding ='post')
print(padded_documents)

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=maxlength))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics =['acc'])

model.summary()

model.fit(padded_documents, labels, verbose=0, epochs=50)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy %f' %(accuracy*100))

[[32, 31], [27, 1, 32, 25, 31], [12, 31], [31, 1, 1], [38], [27, 32], [14, 39], [16, 1], [31, 25, 32], [32, 16, 1]]
[[32 31  0  0  0]
 [27  1 32 25 31]
 [12 31  0  0  0]
 [31  1  1  0  0]
 [38  0  0  0  0]
 [27 32  0  0  0]
 [14 39  0  0  0]
 [16  1  0  0  0]
 [31 25 32  0  0]
 [32 16  1  0  0]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 5, 10)             400       
_________________________________________________________________
flatten_3 (Flatten)          (None, 50)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 451
Trainable params: 451
Non-trainable params: 0
_________________________________________________________________
Accuracy 89.999998
